### ISSUE TITLE
suggestion: show all number circles in mobile's view with Firefox?

### ISSUE THREAD

**Issue by samumist** [mike-st/adapt-carousel-menu#1]
Hello Mike
Thanks for this great menu plugin! I really like it, especially the mouse over number circle to show the module title and the progress indicator on the number circle.

I understand you've turned off the arrow navigation for Firefox. But in the mobile view, it seems impossible to go to the other modules, apart from the first module, from the menu unless you use another navigation extension.

I'm wondering if it is possible to show all the number circles in mobile view?

![adapt version 2 0 demonstration firefoxdeveloperedition today at 12 37 56](https://cloud.githubusercontent.com/assets/3883086/19827249/bf69a1c0-9dd5-11e6-9b2c-0c1f7c4dd52c.png)

**Comment by mike-st** [comment]
Thanks again for this catch also. The thing is you may just need to do a refresh though on this one if you resize the browser window as the arrows are there next to the numbers similar to the cover menu  in mobile view. 
![screenshot](https://cloud.githubusercontent.com/assets/10455453/19864321/1bf3325a-9f6e-11e6-9785-1e1cb2b5d7f7.jpg)


[https://community.adaptlearning.org/learningpool_example2/index.html](https://community.adaptlearning.org/learningpool_example2/index.html)

**Comment by samumist** [comment]
Thanks @mike-st !
I just tested and can confirm that the arrow shows fine on firefox mobile view.
