### ISSUE TITLE
Missing browser scroll bar after refreshing course page

### ISSUE THREAD

**Issue by samumist** [mike-st/adapt-carousel-menu#2]
When refreshing a course page (with Cmd-R on a mac), the right-hand side browser scroll bar is gone and make the user unable to scroll the page. 

This behaviour occurred on both chrome and Firefox with the latest framework and test course. Original boxmenu doesn't have this problem.

**Comment by mike-st** [comment]
Good catch Samumist! I had some old classes for testing in less and js file that I have removed. My bad this is now fixed if you update to the latest version. Thanks again on the catch!

**Comment by samumist** [comment]
Glad to be of a little help and thanks for this great menu!
